### ISSUE TITLE
projects users api & project api

### ISSUE THREAD

**Issue by jpham005** [42Statistics/42Stat-Backend#80]
### API) PROJECT
- `Project` 서클? -> 하드코딩

### API) PROJECT_SESSIONS
- [x] `Project` 서브젝트 pdf (id)
- [x] `Project` TOTAL- 이름 (name)
- [x] `Project` n인 팀 진행 (min/maxUserCount)
- [x] `Project` TOTAL- 사용 기술
- [x] `Project` 설명 (description)
- [x] `Project` 권장 기간 (estimateTime)
- [x] `Project` 경험치 (difficulty)

### API) PROJECTS_USERS
- [x] `Project` TOTAL- 진행중인 팀 수 (currRegisteredTeamCount)
- [x] `home` HOME- 지금 가장 많은 사람이 참여하는 과제 랭킹
- `Landing` 현재 가장 많은 사람이 참여하는 과제와 유저 수: landing page 생기면 작업

### API) TEAMS
- [x] `Project` TOTAL- 누적 총 제출 횟수 (closedTeamCount)
- [x] `Project` TOTAL- 각서브젝트별 통과시 평균 점수 (averagePassFinalMark)
- [x] `Project` TOTAL- pass/fail 비율 (evalInfo)

---

### todo
- [x] project_session schema 만들기
- [x] project_sessions_skills, skills lookup 만들기
- [x] currRegisteredCountRanking filter받게하기
---
😮 
- projectinfo.service -> teamcount는 레지스터한 '팀' 수
- currRegisteredCountRanking
  - teamService.registeredCount() 사용 -> project preview때문에 사용 x
  - url만드는부분 분리?
- project status enum
  - status 반환 없음
- campusId로 project session 찾아서 aggregate를 반환하는걸 만들지... -> 만들고 기존함수 주석으로 둠
- project api에 있던 목록들 project session이랑 시간 비교 후 project session으로 이동 (10ms정도 빠름)
